version: '3.8'

services:
  api:
    build:
      context: .
      target: development
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/api
    depends_on:
      - db
    command: bundle exec puma -C config/puma.rb
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hx71kCBHq2Pg1KeC
      MYSQL_DATABASE: appointment_development
      MYSQL_USER: appointment
      MYSQL_PASSWORD: u8CY3NI39JN0HNaP
    volumes:
      - appointment_mysql_data:/var/lib/mysql
      - .docker/services/db:/docker-entrypoint-initdb.d

volumes:
  appointment_mysql_data:
    driver_opts:
      type: none
      device: ${PWD}/.docker/volumes/db
      o: bind
