name: mf-appointment-api deploy workflow
on:
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build image for tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          target: development
          tags: xistz/mf-appointment-api:development
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - build-test

    container:
      image: xistz/mf-appointment-api:development
      volumes:
        - ${{ github.workspace }}:/api

    env:
      RAILS_ENV: test

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: appointment_test
          MYSQL_USER: appointment
          MYSQL_PASSWORD: u8CY3NI39JN0HNaP
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup db
        run: bundle exec rails db:setup

      - name: Test
        run: bundle exec rspec --format=documentation

  build-deploy:
    name: Build image for deployment
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_EMAIL }}
          password: ${{ secrets.HEROKU_TOKEN }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          target: deployment
          tags: registry.heroku.com/appointment-sample-api/web
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  release:
    name: Release deployment image
    runs-on: ubuntu-latest
    needs:
      - build-deploy

    steps:
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a appointment-sample-api web

  migrate:
    name: Migrate db
    runs-on: ubuntu-latest
    needs:
      - release

    steps:
      - name: Migrate
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku  run -a appointment-sample-api \
                  bundle exec rails db:migrate RAILS_ENV=production
